image: node:12.17.0

stages:
  - develop_deploy
  - release

cache:
  paths:
    - node_modules/

before_script:
  - /bin/bash -c "$(curl -fsSL https://git.heyooo.com/snippets/2/raw)" $NPM_HOST $USERNAME $PASSWORD
  - yarn install

develop_deploy:
  stage: develop_deploy
  only:
    - master
  cache:
    paths:
      - node_modules/
  script: |
    echo "=> Building"
    yarn build
    yarn build:mongoose

    echo "=> Compressing"
    if [ -f h.tar.gz ]; then
      rm h.tar.gz
    fi
    tar --exclude={node_modules,coverage-e2e,src,test,dashboard,*.ts,ecosystem.config.js,README.md} --add-file=.npmrc --add-file=.mongooserc.js -czvf h.tar.gz ./*

    echo "=> Deploying"
    scp -P "$DEVELOP_PORT" -o stricthostkeychecking=no -C h.tar.gz "$DEVELOP_DEPLOY_USER"@"$DEVELOP_DEPLOY_HOST":"$DEVELOP_TEMP"
    DEPLOY_SHELL="tar -xzf ${DEVELOP_TEMP}/h.tar.gz -C ${DEVELOP_APP_DIR} && rm -rf ${DEVELOP_TEMP}/h.tar.gz && cd ${DEVELOP_APP_DIR} && npm config set registry https://npm.cnnic.eu && yarn install --production && yarn start"
    ssh -p "$DEVELOP_PORT" -o stricthostkeychecking=no "$DEVELOP_DEPLOY_USER"@"$DEVELOP_DEPLOY_HOST" -t "$DEPLOY_SHELL"
    exit

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*$/'
  cache:
    paths:
      - node_modules/
  script: |
    echo "=> Building"
    yarn build
    yarn build:mongoose

    echo "=> Compressing"
    if [ -f h.tar.gz ]; then
      rm h.tar.gz
    fi
    tar --exclude={node_modules,coverage-e2e,src,test,dashboard,*.ts,README.md} --add-file=.npmrc --add-file=.mongooserc.js -czvf h.tar.gz ./*

    echo "=> Deploying"
    scp -P "$PRO_DEPLOY_PORT" -o stricthostkeychecking=no -C h.tar.gz "$PRO_DEPLOY_USER"@"$PRO_DEPLOY_HOST":"$PRO_TEMP"
    DEPLOY_SHELL="tar -xzf ${PRO_TEMP}/h.tar.gz -C ${PRO_APP_DIR} && rm -rf ${PRO_TEMP}/h.tar.gz && cd ${PRO_APP_DIR} && npm config set registry https://npm.cnnic.eu && yarn install --production && yarn start"
    ssh -p "$PRO_DEPLOY_PORT" -o stricthostkeychecking=no "$PRO_DEPLOY_USER"@"$PRO_DEPLOY_HOST" -t "$DEPLOY_SHELL"
    exit
